query pokemons($first: Int!) {
  pokemons(first: $first) {
    id
    number
    name
    image
    classification
    types
    resistant
    attacks {
      fast {
        name
        type
        damage
      }
      special {
        name
        type
        damage
      }
    }
    weaknesses
    fleeRate
    maxHP
    maxCP
    weight {
      minimum
      maximum
    }
    height {
      minimum
      maximum
    }
    evolutions {
      name
    }
    evolutionRequirements {
      name
      amount
    }
  }
}
